# ------------------------------------------------------------------
# PlanetScope download configuration
# ------------------------------------------------------------------

# ─── Area of interest ──────────────────────────────────────────────
# Supply *either* an external GeoJSON file path *or* an inline geometry.
# If both are present, the file wins.
aoi:
  # geojson_file: "/home/macula/SMATousi/projects/vigir_remote_sensing/ndvi_calculation/Ellis-Field/Ellis_field_full_extent_soil_survey.geojson"     # path to GeoJSON polygon   (OPTION A)
  geojson_file: "~/Downloads/planet_outline/outline_json.geojson"
  # geometry:                            # inline Polygon            (OPTION B)
  #   type: Polygon
  #   coordinates:
  #     - [
  #         [-90.998541, 39.127731],
  #         [-91.013453, 39.120237],
  #         [-90.999160, 39.113665],
  #         [-90.980979, 39.120784]
  #       ]

# ─── Time window (UTC, ISO-8601) ──────────────────────────────────
# You can specify either:
# 1. Single year with specific dates (original format)
# 2. Multiple years with recurring day timeframe
date_range:
  # Option 1: Single year date range (original format)
  # start: "2015-07-28T00:00:00Z"
  # end:   "2015-08-30T23:59:59Z"
  
  # Option 2: Multiple years with recurring day timeframe
  years:
    start_year: 2025
    end_year: 2025
  day_timeframe:
    start_month: 8    # July
    start_day: 1
    end_month: 8      # August  
    end_day: 31
  time_of_day:
    start: "00:00:00Z"
    end: "23:59:59Z"

# ─── Planet item & asset types ────────────────────────────────────
item_types:
  - PSScene                # 4- or 8-band PlanetScope scenes
asset_types:
  # - ortho_analytic_8b_sr      # surface-reflectance GeoTIFF
  # - ortho_analytic_4b 
  # - analytic_sr
  # - ortho_visual
  - ortho_udm2

# ─── Basic quality filters ────────────────────────────────────────
cloud_cover:

  max: 1         # images with ≤ 5 % cloud_cover

# ─── Download behaviour ───────────────────────────────────────────
output:
  directory: "/home/alitousi/Desktop/PlanetScope_downloads_ortho_sr_udm2_sr/2025"
  clip_to_aoi: true       # set true if you later add a clipping step
  overwrite: false         # skip a file if it already exists
  keep_full_scene: false   # keep the full scene instead of the clip

download:
  max_parallel: 5          # concurrent downloads
  chunk_size: 8192         # bytes per stream chunk
