# ------------------------------------------------------------------
# PlanetScope download configuration
# ------------------------------------------------------------------

# ─── Area of interest ──────────────────────────────────────────────
# Supply *either* an external GeoJSON file path *or* an inline geometry.
# If both are present, the file wins.
aoi:
  geojson_file: "../fields/Ellis_and_BayFarm/Ellis_GeoJSON.geojson"     # path to GeoJSON polygon   (OPTION A)
  # geometry:                            # inline Polygon            (OPTION B)
  #   type: Polygon
  #   coordinates:
  #     - [
  #         [-92.370509,38.981636],
  #         [-92.353630,38.981376],
  #         [-92.356170,38.969190],
  #         [-92.371077,38.968657]
  #       ]

# ─── Time window (UTC, ISO-8601) ──────────────────────────────────
date_range:
  start: "2015-07-28T00:00:00Z"
  end:   "2015-08-30T23:59:59Z"

# ─── Planet item & asset types ────────────────────────────────────
item_types:
  - PSScene                # 4- or 8-band PlanetScope scenes
asset_types:
  # - basic_analytic_8b      # surface-reflectance GeoTIFF
  - ortho_analytic_4b 
  # - analytic_sr
  # - ortho_visual

# ─── Basic quality filters ────────────────────────────────────────
cloud_cover:
  max: 0.05                # images with ≤ 5 % cloud_cover

# ─── Download behaviour ───────────────────────────────────────────
output:
  directory: "./planet_downloads"
  clip_to_aoi: true       # set true if you later add a clipping step
  overwrite: false         # skip a file if it already exists
  keep_full_scene: falses   # keep the full scene instead of the clip

download:
  max_parallel: 2          # concurrent downloads
  chunk_size: 8192         # bytes per stream chunk
